# Generated by Django 5.1.7 on 2026-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTaxEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.JSONField(default=dict)),
                ('entity_type', models.CharField(max_length=40)),
                ('regime_track', models.CharField(max_length=40)),
                ('filing_route', models.CharField(max_length=60)),
                ('decision_trace', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
