# Generated by Django 5.1.7 on 2026-05-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITREvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.JSONField(default=dict)),
                ('selected_form', models.CharField(max_length=20)),
                ('decision_trace', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
