# Generated by Django 5.1.7 on 2026-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0002_itrevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRRegimeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.JSONField(default=dict)),
                ('applicable_regime', models.CharField(max_length=30)),
                ('decision_trace', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
