# Generated by Django 5.1.7 on 2026-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0003_itrregimeevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRTaxComputationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.JSONField(default=dict)),
                ('applicable_regime', models.CharField(max_length=30)),
                ('total_liability', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('decision_trace', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
