from django.urls import path

from .views import (
    AssessmentContextListView,
    ChangeSetActivationReadinessView,
    ChangeSetActivateView,
    ChangeSetApproveView,
    ChangeSetDetailView,
    ChangeSetListView,
    ChangeSetSubmitReviewView,
    CoreRulesIndexView,
    DraftChangeSetBundleView,
    DecisionTableDefinitionListView,
    DecisionTableVersionListView,
    ModuleDefinitionListView,
    ModuleReadinessView,
    ModuleVersionListView,
    PrimitiveVersionSupersedeView,
    RuleDefinitionListView,
    PrimitiveVersionDeleteView,
    PrimitiveVersionApproveView,
    PrimitiveVersionSubmitReviewView,
    RuleVersionDeleteView,
    RuleVersionApproveView,
    RuleVersionSubmitReviewView,
    RuleVersionSupersedeView,
    RuleVersionListView,
)

urlpatterns = [
    path("", CoreRulesIndexView.as_view(), name="core-rules-index"),
    path("assessment-contexts/", AssessmentContextListView.as_view(), name="assessment-context-list"),
    path("rules/", RuleDefinitionListView.as_view(), name="rule-definition-list"),
    path("rule-versions/", RuleVersionListView.as_view(), name="rule-version-list"),
    path("rule-versions/supersede/", RuleVersionSupersedeView.as_view(), name="rule-version-supersede"),
    path(
        "rule-versions/<int:pk>/submit-review/",
        RuleVersionSubmitReviewView.as_view(),
        name="rule-version-submit-review",
    ),
    path("rule-versions/<int:pk>/approve/", RuleVersionApproveView.as_view(), name="rule-version-approve"),
    path("rule-versions/<int:pk>/", RuleVersionDeleteView.as_view(), name="rule-version-delete"),
    path(
        "primitive-versions/supersede/",
        PrimitiveVersionSupersedeView.as_view(),
        name="primitive-version-supersede",
    ),
    path(
        "primitive-versions/<int:pk>/submit-review/",
        PrimitiveVersionSubmitReviewView.as_view(),
        name="primitive-version-submit-review",
    ),
    path(
        "primitive-versions/<int:pk>/approve/",
        PrimitiveVersionApproveView.as_view(),
        name="primitive-version-approve",
    ),
    path("primitive-versions/<int:pk>/", PrimitiveVersionDeleteView.as_view(), name="primitive-version-delete"),
    path("decision-tables/", DecisionTableDefinitionListView.as_view(), name="decision-table-list"),
    path("decision-table-versions/", DecisionTableVersionListView.as_view(), name="decision-table-version-list"),
    path("modules/", ModuleDefinitionListView.as_view(), name="module-definition-list"),
    path("module-versions/", ModuleVersionListView.as_view(), name="module-version-list"),
    path("modules/<str:module_code>/readiness/", ModuleReadinessView.as_view(), name="module-readiness"),
    path("change-sets/", ChangeSetListView.as_view(), name="change-set-list"),
    path("change-sets/draft-bundle/", DraftChangeSetBundleView.as_view(), name="change-set-draft-bundle"),
    path(
        "change-sets/<str:code>/submit-review/",
        ChangeSetSubmitReviewView.as_view(),
        name="change-set-submit-review",
    ),
    path("change-sets/<str:code>/approve/", ChangeSetApproveView.as_view(), name="change-set-approve"),
    path("change-sets/<str:code>/activate/", ChangeSetActivateView.as_view(), name="change-set-activate"),
    path("change-sets/<str:code>/", ChangeSetDetailView.as_view(), name="change-set-detail"),
    path(
        "change-sets/<str:code>/activation-readiness/",
        ChangeSetActivationReadinessView.as_view(),
        name="change-set-activation-readiness",
    ),
]
