# Generated by Django 5.1.7 on 2026-05-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('taxpayer_hash', models.CharField(max_length=128)),
                ('input_payload_hash', models.CharField(max_length=128)),
                ('outcome_payload', models.JSONField(default=dict)),
                ('rule_trace', models.JSONField(blank=True, default=list)),
                ('previous_entry_hash', models.CharField(blank=True, max_length=128)),
                ('entry_hash', models.CharField(max_length=128)),
                ('assessment_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_logs', to='core_rules.assessmentcontext')),
                ('module_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_logs', to='core_rules.moduleversion')),
            ],
            options={
                'ordering': ['-created_at', 'event_id'],
            },
        ),
    ]
