# Generated by Django 5.1.7 on 2026-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationlog',
            name='decision_table_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evaluationlog',
            name='primitive_trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
