# Generated by Django 5.1.7 on 2026-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossModuleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('source_reference', models.CharField(max_length=255)),
                ('natural_language', models.TextField()),
                ('structured_logic', models.JSONField(default=dict)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('depends_on_modules', models.ManyToManyField(blank=True, related_name='cross_module_rules', to='core_rules.moduleversion')),
            ],
            options={
                'ordering': ['rule_id', '-created_at'],
            },
        ),
    ]
