# Generated by Django 5.1.7 on 2026-05-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rules', '0004_alter_moduleversion_status'),
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_payload', models.JSONField(default=dict)),
                ('itr_summary', models.JSONField(default=dict)),
                ('corporate_summary', models.JSONField(default=dict)),
                ('governance_status', models.CharField(max_length=40)),
                ('governance_actions', models.JSONField(default=list)),
                ('rule_trace', models.JSONField(default=list)),
                ('assessment_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_evaluations', to='core_rules.assessmentcontext')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
