# Generated by Django 5.1.7 on 2026-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_governanceevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='governanceevaluation',
            name='governance_summary',
            field=models.JSONField(default=dict),
        ),
    ]
