# Generated by Django 5.1.7 on 2026-05-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('assessment_year', models.CharField(max_length=20)),
                ('financial_year', models.CharField(blank=True, max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('ITR', 'ITR'), ('CORPORATE_TAX', 'Corporate Tax'), ('GOVERNANCE', 'Governance'), ('SHARED', 'Shared')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PrimitiveDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module_scope', models.CharField(choices=[('ITR', 'ITR'), ('CORPORATE_TAX', 'Corporate Tax'), ('GOVERNANCE', 'Governance'), ('SHARED', 'Shared')], max_length=32)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('ITR', 'ITR'), ('CORPORATE_TAX', 'Corporate Tax'), ('GOVERNANCE', 'Governance'), ('SHARED', 'Shared')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('impact_analysis', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_sets', to='core_rules.assessmentcontext')),
            ],
            options={
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('source_reference', models.CharField(max_length=255)),
                ('natural_language', models.TextField()),
                ('structured_logic', models.JSONField(default=dict)),
                ('mode', models.CharField(choices=[('OBSERVER', 'Observer'), ('ALERT', 'Alert'), ('CONTROL', 'Control'), ('DESIGNER', 'Designer')], max_length=16)),
                ('trigger', models.JSONField(blank=True, default=dict)),
                ('consequence', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('ABSOLUTE', 'Absolute')], max_length=16)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core_rules.ruledefinition')),
            ],
            options={
                'ordering': ['rule__rule_id', '-created_at'],
                'unique_together': {('rule', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PrimitiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('completeness_report', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('primitive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core_rules.primitivedefinition')),
                ('rules', models.ManyToManyField(blank=True, related_name='primitive_versions', to='core_rules.ruleversion')),
            ],
            options={
                'ordering': ['primitive__code', '-created_at'],
                'unique_together': {('primitive', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('contract_provides', models.JSONField(blank=True, default=list)),
                ('contract_consumes', models.JSONField(blank=True, default=list)),
                ('fallback_behaviour', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_versions', to='core_rules.assessmentcontext')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core_rules.moduledefinition')),
                ('primitives', models.ManyToManyField(blank=True, related_name='module_versions', to='core_rules.primitiveversion')),
            ],
            options={
                'ordering': ['module__code', '-created_at'],
                'unique_together': {('module', 'version')},
            },
        ),
    ]
