# Generated by Django 5.1.7 on 2026-05-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTableDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('ITR', 'ITR'), ('CORPORATE_TAX', 'Corporate Tax'), ('GOVERNANCE', 'Governance'), ('SHARED', 'Shared')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('module_scope', models.CharField(choices=[('ITR', 'ITR'), ('CORPORATE_TAX', 'Corporate Tax'), ('GOVERNANCE', 'Governance'), ('SHARED', 'Shared')], max_length=32)),
                ('input_columns', models.JSONField(blank=True, default=list)),
                ('output_columns', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('completeness_report', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core_rules.decisiontabledefinition')),
                ('input_primitives', models.ManyToManyField(blank=True, related_name='decision_table_versions', to='core_rules.primitiveversion')),
            ],
            options={
                'ordering': ['decision_table__code', '-created_at'],
                'unique_together': {('decision_table', 'version')},
            },
        ),
        migrations.AddField(
            model_name='moduleversion',
            name='decision_tables',
            field=models.ManyToManyField(blank=True, related_name='module_versions', to='core_rules.decisiontableversion'),
        ),
    ]
