# Generated by Django 5.1.7 on 2026-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rules', '0002_decisiontabledefinition_decisiontableversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='activation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='changeset',
            name='decision_table_versions',
            field=models.ManyToManyField(blank=True, related_name='change_sets', to='core_rules.decisiontableversion'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='module_versions',
            field=models.ManyToManyField(blank=True, related_name='change_sets', to='core_rules.moduleversion'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='primitive_versions',
            field=models.ManyToManyField(blank=True, related_name='change_sets', to='core_rules.primitiveversion'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='rule_versions',
            field=models.ManyToManyField(blank=True, related_name='change_sets', to='core_rules.ruleversion'),
        ),
    ]
