# Generated by Django 5.1.7 on 2026-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rules', '0003_changeset_activation_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20),
        ),
    ]
